spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit

logging:
  level:
    org.springframework.wep: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG